package com.mindtree.springexamplev2.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName = "newtablde1")
public class EntityClassForDynamo {

	private int id;

	private String name;
	private String lastName;
	private String email;
	private String password;
	private String UniqueIdentifer;
	@DynamoDBAttribute(attributeName = "UniqueIdentifer")
	public String getUniqueIdentifer() {
		return UniqueIdentifer;
	}

	public void setUniqueIdentifer(String UniqueIdentifer) {
		this.UniqueIdentifer = UniqueIdentifer;
	}

	public EntityClassForDynamo(String name, String lastName, String email, String password,String UniqueIdentifer) {
		super();

		this.name = name;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.UniqueIdentifer=UniqueIdentifer;
	}

	public EntityClassForDynamo() {
		super();

	}

	@DynamoDBHashKey(attributeName = "email")
	@DynamoDBAutoGeneratedKey
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@DynamoDBAttribute(attributeName = "id")
	@DynamoDBVersionAttribute
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "lastname")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBAttribute(attributeName = "password")
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
